Update CI-Pipeline.yml

diff --git a/.github/workflows/CI-Pipeline.yml b/.github/workflows/CI-Pipeline.yml
--- a/.github/workflows/CI-Pipeline.yml
+++ b/.github/workflows/CI-Pipeline.yml
@@ -40,11 +40,37 @@ jobs:
           BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
           COMMIT_SHORT_SHA=$(git rev-parse --short=7 HEAD)
           docker build -t noabt/myapp:${BRANCH_NAME}-${COMMIT_SHORT_SHA} .
+          yq eval '.app.image.tag = env(BRANCH_NAME) + "-" + env(COMMIT_SHORT_SHA)' -i docker-compose.yaml
 
-      - name: Test the image inside an envaironment
+      - name: set git config
         run: |
-           docker run -d 
+          git config --global user.email "noabt123@gmail.com"
+          git config --global user.name "noa"
 
+      - name: stage changed files
+        run: |
+          git add .
+          git commit -m "Auto updating docker-compose.yaml"
+          git pull origin main
+          git push origin HEAD:main
+
+      - name: Test the connection between the new app image and the db
+        run: |
+           docker-compose up -d
+           sleep 20
+           docker-compose up -d
+           sleep 20
+
+      - name: Check Response Code
+        run: |
+          APP_RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:3000)
+          if [ "$APP_RESPONSE" -eq 302 ]; then
+            echo "App is running and returning a 302 response code."
+          else
+            echo "Connection to the app failed. Response code: $APP_RESPONSE"
+            exit 1
+          fi
+          
       - name: Login to Docker Hub
         uses: docker/login-action@v2.2.0
         with:
@@ -63,21 +89,12 @@ jobs:
           export COMMIT_SHORT_SHA=$(git rev-parse --short HEAD)
           yq eval '.app.image.tag = env(BRANCH_NAME) + "-" + env(COMMIT_SHORT_SHA)' -i myapp/values.yaml
 
-      - name: set git config
+      - name: update the changes
         run: |
-          git config --global user.email "noabt123@gmail.com"
-          git config --global user.name "noa"
+          git add .
+          git commit -m "Auto updating values.yaml"
+          git pull origin main
+          git push origin HEAD:main
         
-      - name: stage changed files
-        run: git add .
-        
-      - name: commit changed files
-        run: git commit -m "Auto updating values.yaml"
-        
-      - name: fetch from master
-        run: git pull origin main
-        
-      - name: push code to master
-        run: git push origin HEAD:main
-
+     
 
